---
- hosts: webservers
  become: yes
  tasks:
  - name: disply the  host name
    command: hostname -f
    register: myresult
  
  - name: disply the myresult
    debug:
      msg: "{{ myresult }}"

  - name: install git
    yum:
      name: git
      state: present
    when: myresult.stderr ==""

  - name: install tree
    yum:
      name: tree
      state: present
    when: myresult.stderr !=""
