---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webservers
    yum:
      name: httpd
      state: present
    notify: startwebservers

  - name: copy the dynamic file
    template:
      src: myindex.j2
      dest: /var/www/html/index.html 
    notify: startwebservers

  handlers:
  - name: startwebservers
    service:
      name: httpd
      state: started
  
  